FROM centos:7.2.1511
MAINTAINER jesada gonkratoke "jesada.gon@ascendcorp.com"

ENV container docker
RUN yum -y update; yum clean all
RUN yum -y install systemd; yum clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/sbin/init"]

# docker build -t centos7:systemd .

-------------------------------------------------------
FROM centos7:systemd
MAINTAINER jesada gonkratoke "jesada.gon@ascendcorp.com"

RUN mkdir /temp
COPY jdk-8u73-linux-x64.rpm /temp
RUN rpm -ivh /temp/jdk-8u73-linux-x64.rpm
RUN groupadd tomcat
RUN useradd -M -s /bin/nologin -g tomcat -d /opt/tomcat tomcat
COPY apache-tomcat-8.0.32.tar.gz /temp
RUN mkdir /opt/tomcat
RUN tar xvf /temp/apache-tomcat-8.0.32.tar.gz -C /opt/tomcat --strip-components=1
RUN cd /opt/tomcat
RUN chown -R tomcat:tomcat /opt/tomcat
RUN chmod -R 777 /opt/tomcat
COPY tomcat.service /etc/systemd/system/tomcat.service
RUN sed -i -e 's/\/usr\/lib\/jvm\/jre/\/usr\/java\/jdk1.8.0_73\/jre/g' /etc/systemd/system/tomcat.service
COPY tomcat-users.xml /opt/tomcat/conf/tomcat-users.xml
COPY v1/hello /opt/tomcat/webapps/hello
COPY v1/hello.war /opt/tomcat/webapps
RUN chown -R tomcat:tomcat /opt/tomcat/webapps/hello
RUN chown -R tomcat:tomcat /opt/tomcat/webapps/hello.war
RUN systemctl enable tomcat

EXPOSE 8080
CMD ["/usr/sbin/init"]

# docker build -t centos7:hellov1 .
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

FROM centos7:systemd
MAINTAINER jesada gonkratoke "jesada.gon@ascendcorp.com"

RUN mkdir /temp
COPY jdk-8u73-linux-x64.rpm /temp
RUN rpm -ivh /temp/jdk-8u73-linux-x64.rpm
RUN groupadd tomcat
RUN useradd -M -s /bin/nologin -g tomcat -d /opt/tomcat tomcat
COPY apache-tomcat-8.0.32.tar.gz /temp
RUN mkdir /opt/tomcat
RUN tar xvf /temp/apache-tomcat-8.0.32.tar.gz -C /opt/tomcat --strip-components=1
RUN cd /opt/tomcat
RUN chown -R tomcat:tomcat /opt/tomcat
RUN chmod -R 777 /opt/tomcat
COPY tomcat.service /etc/systemd/system/tomcat.service
RUN sed -i -e 's/\/usr\/lib\/jvm\/jre/\/usr\/java\/jdk1.8.0_73\/jre/g' /etc/systemd/system/tomcat.service
COPY tomcat-users.xml /opt/tomcat/conf/tomcat-users.xml
COPY v2/hello /opt/tomcat/webapps/hello
COPY v2/hello.war /opt/tomcat/webapps
RUN chown -R tomcat:tomcat /opt/tomcat/webapps/hello
RUN chown -R tomcat:tomcat /opt/tomcat/webapps/hello.war
RUN systemctl enable tomcat

EXPOSE 8080
CMD ["/usr/sbin/init"]

# docker build -t centos7:hellov2 .
